CVControl.UI/Areas/Admin/Controllers/EstatisticasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CVControl.Application;
using Newtonsoft.Json;

namespace CVControl.UI.Areas.Admin.Controllers
{
    public class EstatisticasController : Controller
    {
        private readonly ResultadoApp _resultadoApp;

        public EstatisticasController()
        {
            _resultadoApp = new ResultadoApp();
        }
        // GET: Admin/Estatisticas
        public ActionResult Index()
        {
            ViewBag.Genero = JsonConvert.SerializeObject(_resultadoApp.GerarDataGenero());
            ViewBag.EstadoCivil = JsonConvert.SerializeObject(_resultadoApp.GerarDataEstadoCivil());
            ViewBag.Idade = JsonConvert.SerializeObject(_resultadoApp.GerarDataIdade());
            ViewBag.Filhos = JsonConvert.SerializeObject(_resultadoApp.GerarDataFilhos());
            ViewBag.Provincia = JsonConvert.SerializeObject(_resultadoApp.GerarDataProvincias());

            return View();
        }
    }
}

CVControl.UI/Areas/Admin/Controllers/ExportarController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CVControl.UI.Areas.Admin.Controllers
{
    public class ExportarController : Controller
    {
        // GET: Admin/Exportar
        public ActionResult Index()
        {
            return View();
        }
    }
}

CVControl.UI/Areas/Admin/Controllers/InicioController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CVControl.Application;
using Newtonsoft.Json;

namespace CVControl.UI.Areas.Admin.Controllers
{
    public class InicioController : Controller
    {
        private readonly ResultadoApp _resultadoApp;

        public InicioController()
        {
            _resultadoApp = new ResultadoApp();
        }
        
        public ActionResult Index()
        {
            ViewBag.Data = JsonConvert.SerializeObject(_resultadoApp.GerarDataHistorico()); ;

            return View(_resultadoApp.CalcularEstatisticas());
        }
    }
}

CVControl.UI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="COVID 19 Monitor">
    <meta name="author" content="Digital Factory">

    <title>CVControl</title>

    <!-- Custom fonts for this template-->
    <link href="~/Assets/plugins/fontawesome-free/css/all.min.css" rel="stylesheet" />
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

    <!-- Custom styles for this template-->
    @*<link href="css/sb-admin-2.min.css" rel="stylesheet">*@
    <link href="~/Assets/css/sb-admin-2.min.css" rel="stylesheet" />

</head>

<body id="page-top">
    <!-- Page Wrapper -->
    <div id="wrapper">
        <!-- Sidebar -->
        <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">
            <!-- Sidebar - Brand -->
            <a class="sidebar-brand d-flex align-items-center justify-content-center" href="@Url.Action("Index","Inicio", new {Area ="Admin"})">
                <div class="sidebar-brand-icon rotate-n-15">
                    <i class="fas fa-medkit"></i>
                </div>
                <div class="sidebar-brand-text mx-3">CVControl<sup>2</sup></div>
            </a>
            <!-- Divider -->
            <hr class="sidebar-divider my-0">
            <!-- Nav Item - Dashboard -->
            <li class="nav-item active">
                <a class="nav-link" href="@Url.Action("Index","Inicio", new {Area ="Admin"})">
                    <i class="fas fa-fw fa-home"></i>
                    <span>Inicio</span>
                </a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="@Url.Action("Index","Estatisticas", new {Area ="Admin"})">
                    <i class="fas fa-fw fa-chart-bar"></i>
                    <span>Estatisticas Gerais</span>
                </a>
            </li>

            <li class="nav-item active">
                <a class="nav-link" href="@Url.Action("Index","Exportar", new {Area ="Admin"})">
                    <i class="fas fa-fw fa-download"></i>
                    <span>Exportar</span>
                </a>
            </li>
            <!-- Divider -->
            <hr class="sidebar-divider d-none d-md-block">

            <!-- Sidebar Toggler (Sidebar) -->
            <div class="text-center d-none d-md-inline">
                <button class="rounded-circle border-0" id="sidebarToggle"></button>
            </div>

        </ul>
        <!-- End of Sidebar -->
        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">

                <!-- Topbar -->
                <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

                    <!-- Sidebar Toggle (Topbar) -->
                    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
                        <i class="fa fa-bars"></i>
                    </button>

                    <!-- Topbar Navbar -->
                    <ul class="navbar-nav ml-auto">
                        
                        <div class="topbar-divider d-none d-sm-block"></div>

                        <!-- Nav Item - User Information -->
                        <li class="nav-item dropdown no-arrow">
                            <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <span class="mr-2 d-none d-lg-inline text-gray-600 small">Administrador</span>
                                <img class="img-profile rounded-circle" src="https://source.unsplash.com/QAB-WJcbgJk/60x60">
                            </a>
                            <!-- Dropdown - User Information -->
                            <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="userDropdown">
                                <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">
                                    <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Logout
                                </a>
                            </div>
                        </li>

                    </ul>

                </nav>
                <!-- End of Topbar -->
                <!-- Begin Page Content -->
                <div class="container-fluid">

                    <!-- Page Heading -->
                    <h1 class="h3 mb-4 text-gray-800">@ViewBag.Title</h1>
                    @RenderBody()
                </div>
                <!-- /.container-fluid -->

            </div>
            <!-- End of Main Content -->
            <!-- Footer -->
            <footer class="sticky-footer bg-white">
                <div class="container my-auto">
                    <div class="copyright text-center my-auto">
                        <span>Copyright &copy; @DateTime.Now.Year</span>
                    </div>
                </div>
            </footer>
            <!-- End of Footer -->

        </div>
        <!-- End of Content Wrapper -->

    </div>
    <!-- End of Page Wrapper -->
    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>

    <!-- Logout Modal-->
    <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Confirmar saida</h5>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">Está prestes a terminar a sua sessão.</div>
                <div class="modal-footer">
                    <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancelar</button>
                    <a class="btn btn-primary" href="#">Sair</a>
                </div>
            </div>
        </div>
    </div>

    <script src="~/Assets/plugins/jquery/jquery.min.js"></script>
    <script src="~/Assets/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="~/Assets/plugins/jquery-easing/jquery.easing.min.js"></script>
    <script src="~/Assets/js/sb-admin-2.min.js"></script>
</body>

</html>